name: "DataAPI-Java"
version: ${project.version}
main: codes.laivy.data.main.BukkitPlugin
author: "ItsLaivy (DanielZinh#7616)"
api-version: 1.13

website: "https://laivy.codes/"

libraries:
  - biz.paluch.redis:lettuce:4.5.0.Final
  - org.xerial:sqlite-jdbc:3.40.0.0
  - mysql:mysql-connector-java:8.0.30